#!/usr/bin/env bash
set -euo pipefail

TASK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/context.sh
source "$TASK_DIR/../../lib/context.sh"

DOTNET_ROOT="$DOTNET_ROOT" DOTNET_ROOT_ARM64="$DOTNET_ROOT_ARM64" \
  "$DOTNET_EXE" run \
    --project "$TUFHELPER_LITE_PROJECT_ROOT/TUFHelperLite.Tests/TUFHelperLite.Tests.csproj" \
    -p:AdofaiManaged="$ADOFAI_MANAGED" \
    -p:AdofaiMods="$ADOFAI_MODS_DIR" \
    -p:AdofaiIpcDll="$ADOFAIIPC_DLL" \
    -p:UnityModManagerDll="$UNITY_MOD_MANAGER_DLL" \
    -p:HarmonyDll="$HARMONY_DLL"

TUFHELPER_LITE_CORE_DLL="$TUFHELPER_LITE_BUILD_OUTPUT/TUFHelperLite.Core.dll" \
TUFHELPER_LITE_LAUNCHER_DLL="$TUFHELPER_LITE_LAUNCHER_BUILD_OUTPUT/TUFHelperLite.Launcher.dll" \
TUFHELPER_LITE_UPDATE_ENGINE_DLL="$TUFHELPER_LITE_UPDATE_ENGINE_BUILD_OUTPUT/TUFHelperLite.UpdateEngine.dll" \
TUFHELPER_LITE_INFO_JSON="$TUFHELPER_LITE_PROJECT_ROOT/TUFHelperLite/Info.json" \
ADOFAIIPC_BOOTSTRAP_DLL="$ADOFAIIPC_BOOTSTRAP_DLL" \
ADOFAIIPC_DEPENDENCY_SHIM_DLL="$ADOFAIIPC_DEPENDENCY_SHIM_DLL" \
ADOFAIIPC_MIGRATION_DLL="$ADOFAIIPC_MIGRATION_DLL" \
DOTNET_ROOT="$DOTNET_ROOT" DOTNET_ROOT_ARM64="$DOTNET_ROOT_ARM64" \
  "$DOTNET_EXE" run \
    --project "$TUFHELPER_LITE_PROJECT_ROOT/TUFHelperLite.UpdateTests/TUFHelperLite.UpdateTests.csproj" \
    -p:AdofaiManaged="$ADOFAI_MANAGED" \
    -p:UnityModManagerDll="$UNITY_MOD_MANAGER_DLL"
