#!/usr/bin/env bash

if [ "${TUFHELPER_LITE_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
TUFHELPER_LITE_CONTEXT_LOADED=1

TUFHELPER_LITE_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TUFHELPER_LITE_PROJECT_ROOT="$(cd "$TUFHELPER_LITE_LIB_DIR/../.." && pwd)"

if [ -f "$TUFHELPER_LITE_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$TUFHELPER_LITE_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"
ADOFAIIPC_DLL="${ADOFAIIPC_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.dll}"
ADOFAIIPC_BOOTSTRAP_DLL="${ADOFAIIPC_BOOTSTRAP_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.Bootstrap.dll}"
ADOFAIIPC_DEPENDENCY_SHIM_DLL="${ADOFAIIPC_DEPENDENCY_SHIM_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.DependencyShim.dll}"
ADOFAIIPC_MIGRATION_DLL="${ADOFAIIPC_MIGRATION_DLL:-$ADOFAI_MODS_DIR/AdofaiIpc/AdofaiIpc.Migration.dll}"
ADOFAIIPC_INFO_JSON="${ADOFAIIPC_INFO_JSON:-$ADOFAI_MODS_DIR/AdofaiIpc/Info.json}"
ADOFAIIPC_BOOTSTRAP_LOCK="$TUFHELPER_LITE_PROJECT_ROOT/TUFHelperLite/AdofaiIpcBootstrap.lock"

TUFHELPER_LITE_BUILD_OUTPUT="${TUFHELPER_LITE_BUILD_DIR:-$TUFHELPER_LITE_PROJECT_ROOT/build/TUFHelperLite}"
TUFHELPER_LITE_LAUNCHER_BUILD_OUTPUT="${TUFHELPER_LITE_LAUNCHER_BUILD_DIR:-$TUFHELPER_LITE_PROJECT_ROOT/build/TUFHelperLite.Launcher}"
TUFHELPER_LITE_UPDATE_ENGINE_BUILD_OUTPUT="${TUFHELPER_LITE_UPDATE_ENGINE_BUILD_DIR:-$TUFHELPER_LITE_PROJECT_ROOT/build/TUFHelperLite.UpdateEngine}"
TUFHELPER_LITE_INSTALL_PATH="${TUFHELPER_LITE_INSTALL_DIR:-$ADOFAI_MODS_DIR/TUFHelperLite}"
TUFHELPER_LITE_PACKAGE_ROOT="${TUFHELPER_LITE_PACKAGE_ROOT:-$TUFHELPER_LITE_PROJECT_ROOT/build/package}"
TUFHELPER_LITE_PACKAGE_STAGE="$TUFHELPER_LITE_PACKAGE_ROOT/TUFHelperLite"
TUFHELPER_LITE_PACKAGE_ZIP="${TUFHELPER_LITE_PACKAGE_ZIP:-$TUFHELPER_LITE_PROJECT_ROOT/build/TUFHelperLite.zip}"

export TUFHELPER_LITE_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE
export UNITY_MOD_MANAGER_DLL HARMONY_DLL
export ADOFAIIPC_DLL ADOFAIIPC_BOOTSTRAP_DLL ADOFAIIPC_DEPENDENCY_SHIM_DLL
export ADOFAIIPC_MIGRATION_DLL
export ADOFAIIPC_INFO_JSON ADOFAIIPC_BOOTSTRAP_LOCK
export TUFHELPER_LITE_BUILD_OUTPUT TUFHELPER_LITE_LAUNCHER_BUILD_OUTPUT
export TUFHELPER_LITE_UPDATE_ENGINE_BUILD_OUTPUT
export TUFHELPER_LITE_INSTALL_PATH TUFHELPER_LITE_PACKAGE_ROOT
export TUFHELPER_LITE_PACKAGE_STAGE TUFHELPER_LITE_PACKAGE_ZIP
